services:
  cdk:
    build: .
    image: cdk-gihyo-toreca
    volumes:
      - .:/work
      - ~/.aws:/root/.aws
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true